# Generated by Django 3.1.3 on 2021-03-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='animal_sponsor',
            options={'verbose_name': 'Apadrinamiento de animal', 'verbose_name_plural': 'Apadrinamientos de animales'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_id',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='lifestage',
        ),
        migrations.AddField(
            model_name='animal',
            name='course',
            field=models.IntegerField(default=0, verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='document',
            field=models.FileField(default=0, upload_to='Documentos', verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='instrucciones',
            field=models.TextField(default=0, verbose_name='Instrucciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='rut',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='RUT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='school',
            field=models.IntegerField(default=0, verbose_name='Colegio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='sponsors',
            field=models.ManyToManyField(through='shelter.Animal_sponsor', to='shelter.Sponsor', verbose_name='Apadrinamientos'),
        ),
        migrations.AlterField(
            model_name='animal_sponsor',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='animal_sponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.sponsor', verbose_name='Apadrinamiento'),
        ),
    ]
