# Generated by Django 3.1.7 on 2021-03-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('school', models.IntegerField(verbose_name='Colegio')),
                ('course', models.IntegerField(verbose_name='Curso')),
                ('instruction', models.TextField(verbose_name='Instrucciones')),
                ('image', models.ImageField(upload_to='Animales', verbose_name='Imagen')),
                ('document', models.FileField(upload_to='Documentos', verbose_name='Documento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
