# Generated by Django 3.1.7 on 2021-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.URLField(default=2, verbose_name='Enlace'),
            preserve_default=False,
        ),
    ]
