# Generated by Django 3.1.7 on 2021-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_activity_namelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Documentos', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='instruction',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='namelink',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de enlace'),
        ),
    ]
