# Generated by Django 3.1.7 on 2021-03-10 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Perfiles', verbose_name='Imagen')),
                ('fname', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Curso')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Profile_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.activity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
            options={
                'verbose_name': 'Actividad de estudiante',
                'verbose_name_plural': 'Actividades de estudiantes',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='activityToStudent',
            field=models.ManyToManyField(through='registration.Profile_activity', to='shelter.Activity', verbose_name='Actividades por estudiante'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
